name: build

on:
    push:
        branches: [Unit-Test]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 7.0.x

            - name: Install dependencies
              run: dotnet restore
              working-directory: src/SampleLibrary

            - name: Build
              run: dotnet build --configuration Release --no-restore
              working-directory: src/SampleLibrary

            - name: Test
              run: dotnet test --no-restore --verbosity d --collect:"XPlat Code Coverage"
              working-directory: src/SampleLibrary
            - name: Publish code coverage reports to codecove.io
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./**/coverage.cobertura.xml
                  fail_ci_if_error: true
